#+TITLE: Планирование и учёт бюджета времени
#+AUTHOR: Александр Любищев

* Планирование и учёт бюджета времени

** Необходимость системы

По этому вопросу имеется много книжек и одно время, в 20-х годах, была
"Лига времени" (Эльве), которая ставила своей целью учет времени в
целях планомерного его использования.

Известно также, что существует особая дисциплина, так называемая
научная организация труда, широко применяемая на фабриках и заводах с
целью рационализации труда и сокращения себестоимости продукта
производства. Она основана на хронометраже всех процессов изготовления
какого-либо изделия и сокращения всех тех затрат времени, которые не
являются непосредственно производительными. В 20-х годах и в вузах
ставился вопрос о научной организации или "нотизации" педагогического
и научного труда. Как и многие другие полезные начинания, это движение
скоро прекратилось и сейчас о нем помнят только немолодые люди. Такая
неудача объясняется рядом причин: тем, что велась эта работа в порядке
кампанейщины, руководили этой работой лица, не имеющие в этом деле
одыта, и учет производился в порядке уравниловки: все виды
времяпрепровождения учитывались с одинаковой точностью, это было
весьма обременительно, отчего даже опытным лицам невозможно было
придерживаться этой системы долгое время.

Я здесь изложу свою систему, поскольку она основана на
тридцатишестилетнем опыте. Начал я вести учет своего времени с
1.1.1916г. и с тех пор веду его регулярно, регулярно записываю все,
что мной сделано. Часть моих записей пропала, у меня сохранились
записи с 1937г. по настоящий день. За 12 лет (1937--1948гг.) краткие
записи составляют два тома. Обычно я записываю в записной книжке все,
что мной проделано за день, а потом перепечатываю на машинке.  Моя
система является оригинальной, так как из всех моих многочисленных
знакомых я не знаю никого, кто бы такой системой учета
пользовался. Один из моих друзей как-то сказал мне: "Какой смысл себя
обрекать на добровольную каторгу!" Но я к этом системе привык и без
этой системы я работать не могу.

Причины, которые заставили меня прибегнуть к этой системе, являются в
значительной мере индивидуальными. Во-первых, это то, что довольно с
раннего возраста интересовался разнообразными вопросами и по
сегодняшний день у меня интересы не снижаются, а расширяются и,
естественно, для того, чтобы уложиться мне пришлось заняться
планированием моей работы. Я думаю, что этой индивидуальной чертой
обладают многие. В прежнее время господствующим типом ученого был
узкий специалист, и мы знаем, что большинство ученых работали без
системы учета и достигали крупных результатов. Сейчас дело изменилось.
Разнообразные отрасли наук связаны между собой, ставится упор на
создание гармонически развитого человека, а не узкого человека,
человека, имеющего понятие о философии и о науках, смежных с его
основной специальностью.  В то время люди, разносторонне развитые, не
были типичными, а сейчас они должны быть типичными.

Поэтому я считаю в праве изложить свою систему, поскольку она может
помочь молодым работникам в планировании их работы. Я не считаю
обязательным ее применение, но кто ею интересуется, тот может
попробовать ее применить.

Очень многие говорят, что не хватает времени, например, на изучение
иностранных языков. Для всякого человека, а в особенности для молодого
научного работника, времени всегда хватать не будет, если он не будет
его планировать. При отсутствии организованности, в смысле
планирования своего времени, не сразу можно сообразить, чем можно
заняться.

Будучи молодым человеком, в университете, я решил заниматься
математикой самостоятельно, поскольку математики в университете на
нашем факультете не было, так как считали, что математика не связана с
биологией. Я же убежден в необходимости расширения и углубления
математических знаний, и однажды летом я задумал заниматься
математикой. Примитивное планирование свойственно каждому человеку, и
в то лето (если не ошибаюсь, это был 1910 год) я глазомерно
планировал, наряду с летним отдыхом сборы насекомых, занятие языками,
занятия математикой и т.д. Прошел месяц, и я убедился, что сделал
очень мало. У меня возникла мысль, что я мало способен к математике,
так как по моим планам я должен посвящать достаточно времени. Тогда я
попробовал подсчитать, сколько же времени я затрачиваю фактически на
занятия математикой.  И оказалось, что фактически я потратил времени
гораздо меньше, чем предполагал и что дело объясняется не полным
отсутствием способностей, а неумением планировать время.  С тех пор я
начал записывать время, потраченное мной на тот или иной вид
умственной работы, а с 1 января 1916 года я стал записывать с разной
степенью точности весь результат каждого дня. не делая исключений и
для выходных дней. Я пишу время начала данной работы и время окончания
ее, причем пишу с точностью до 5 минут. Всякие перерывы в работе я
выключаю, я подсчитываю время нетто.  Время нетто получается гораздо
меньше количества времени, которое получается из расчета времени
брутто, то есть того времени, которое вы провели за данной работой.

Часто люди говорят, что они работают по 14--15 часов. Может быть,
такие люди и существуют, но мне не удавалось столько проработать с
учетом времени нетто.  Рекорд продолжительности моей научной работы 11
час. 30 мин. Обычно я бываю доволен, когда проработаю нетто 7--8
часов. Самый рекордный месяц у меня был в июле 1937 года, когда я за
один месяц проработал 216 часов, то есть в среднем по 7 часов
нетто. Если время нетто перевести во время брутто, то надо прибавить
процентов 25--30. Постепенно я совершенствовал свой учет и в конце
концов пришел к той системе, которая имеет место сейчас.

** Моя система планирования и учета времени

В принципе моя система заключается в следующем. Составляю план работы,
веду учет времени, то есть контроль выполнения плана, что является
очень важным. В то время, когда я начал заниматься планированием
научной работы, о планировании ее никто не говорил.  А поэтому, когда
меня иногда упрекают, что я не планирую научной работы, то я обычно
отвечаю, что я этим начал заниматься тогда, когда об этом большинство
и не догадывалось думать.

Основное в каждом планировании --- это контроль за выполнением
плана. Часто планируют научную работу, но контроль за выполнением
научной работы порой отсутствует.

Далеко не всегда удается план выполнить полностью, но иногда удается и
перевыполнить.

Каковы принципы такого планирования и учета?

1. Точность учета работы должна соответствовать качеству данной
   работы.
2. Работу надо распределять так, чтобы на каждую работу использовать
   время соответствующей квалификации.
3. Использовать "отбросы времени".
4. Постоянно тренироваться в смысле повышения организации труда.

Что касается общего планирования, то при планировании учитывается
прошлый опыт и точность учета соответствует степени использованного
времени. Поясню это.

В "Лиге времени" был крупный дефект, заключающийся в следующем. Там
все времяпрепровождение подсчитывалось с одинаковой точностью:
столько-то времени на сон, столько-то --- на еду, столько-то --- на
одевание, столько-то --- на научную работу и т.п. Этого делать не
следовало. Естественно, что каждый человек должен спать каждый день,
должен есть, то есть он тратит время на стандартное
времяпрепровождение.  Опыт работы показывает, что примерно 12--13
часов брутто можно использовать на нестандартные способы
времяпрепровождения: на работу служебную, работу научную, работу
общественную, на развлечения и т.д.  Поэтому я строю план
распределения времени с точностью до половины вечернего эквивалента
(это мой термин).  Мы знаем, что существуют три отрезка активного
времени: утро, день, вечер. В этих отрезках времени, называемых
вечерними эквивалентами, я и распределяю свое время; только с этой
точностью я и распределяю значительную часть своего времени, как-то:
работу в пединституте --- лекции, заседания кафедры и т.д. Это
служебная работа, необходимая, важная, но не являющаяся прямой научной
работой.  Затем общественная работа: участие в научных обществах,
собраниях; следующий раздел --- переезды с места на место,
командировки, развлечения, домашние дела, отдых, общение с людьми;
болезни --- особый раздел, планированием не предусмотренный, это
экстренный случай.

Научная работа в прямом ее смысле учитывается по пяти разделам с
точностью до 5 минут.

У меня в плане есть такие разделы:
1. Основная научная работа: работа по биологии, по философии, по
   математике и т.д. Это работа или необходимая для выполнения плана,
   или необходимая для повышения квалификации и для ознакомления с
   определенными отраслями науки.
2. Педагогическая биология и популяризация (оригинальная).
   Биологические знания, которые нужны непосредственно для подготовки
   к лекциям, я включаю в научную работу. Этим я освежаю свои знания в
   данной отрасли и попутно у меня возникают разные соображения,
   которые имеют значение для развития тех или иных тем.
3. Экология и прикладная биология.
4. Систематика насекомых. В этом разделе значатся: экскурсии, сбор
   насекомых, монтировка их, определение, обработка.
5. Органинизационная работа: составление отчетов, планов, приведение в
   порядок всех своих дел.

При составении годовых и месячных планов приходится руководствоваться
накопленным опытом. Например, я планирую прочесть такую-то книгу. По
старому опыту я знаю, что в час я прочитываю 20--30 страниц. На
основании старого опыта я и планирую. Напротив, по математике я
планирую прочитать 4--5 стр. в час, а иногда и меньше страниц.

Все прочитанное я стараюсь проработать. В чем заключается проработка?
Если книга касается нового предмета, мало мне известного, то я
стараюсь проконспектировать. Стараюсь на каждую более или менее
серьезную книгу написать критический реферат. На основе прошлого опыта
можно наметить для проработки известное количество книг.

При серьезном отношении к делу обычно отклонение фактически
проработанного времени от намеченного бывает в 10%. Часто бывает, что
не удается проработать намеченное количество книг, создается большая
задолженность. Часто появляются новые интересы, а потому задолженность
бывает велика и скоро ликвидировать ее невозможно, а потому имеет
место невыполнение плана. Бывает невыполнение плана по причине
временного упадка работоспособности. Бывают внешние причины
невыполнения плана, но во всяком случае мне ясно, что планировать свою
работу необходимо и я думаю, что многое из того, чего я достиг,
объясняется моей системой.

** Примеры

Приведу примеры учета времени из собственной практики. В 1925 году в
мае месяце был произведен тщательный автохронометраж всего времени и
результат оказался следующим:


|                                                                                         |                   |
|-----------------------------------------------------------------------------------------+-------------------|
| 1. прямая педагогическая работа (лекции, семинары)                                      | 20ч. 10м.         |
| 2. подготовка к педагогической работе                                                   | 12ч. 15м.         |
| 3. участие в комиссиях и совещаниях, непосредственно связанных с педагогической работой | 13ч. 40м.         |
| 4. экзамены, зачеты и проверка письменных работ                                         | 13ч. 45м.         |
| 5. административная работа (зам. декана педфака и учен. секретарь Биологического ин-та) | 80ч. 40м.         |
| 6. чтение научной литературы и подготовка научных работ                                 | 66ч. 50м.         |
| 7. служебные переезды и переходы                                                        | 48ч. 15м.         |
| 8. профессиональная и общественная работа                                               | 36ч. 50м.         |
| 9. научные общества                                                                     | 6ч. 05м.          |
| 10. сон                                                                                 | 249ч. 55м.        |
| 11. отдых и культурные развлечения (театры, кино, лекции, экскурсии)                    | 45ч. 05м.         |
| 12. принятие пищи                                                                       | 58ч. 30м.         |
| 13. домашние дела, общение с людьми и прочие непредвиденные формы затраты времени       | 87ч.              |
|-----------------------------------------------------------------------------------------+-------------------|
|                                                                                         | Всего 744ч.00м.   |

Такой учет с одинаковой степенью точности всего времени крайне
утомителен и я его проделал только раз, за один месяц.

Пример более грубого учета привожу за июль 1937 года, причем не скрою,
что это был самый продуктивный месяц за все время учета с 1 января
1916 года. Грубый учет велся в "вечерних эквивалентах" (один день
равен трем вечерним эквивалентам).

|                                                                                           | Намечено по плану | Выполнено |
|-------------------------------------------------------------------------------------------+-------------------+-----------|
| Основная научная рвбота                                                                   |              10.0 |      11.0 |
| Экология и прикладная биология                                                            |              31.5 |      25.5 |
| Систематическая энтомология                                                               |              23.5 |      29.0 |
| Организационная работа                                                                    |               1.0 |       1.0 |
| Зоолог. Институт АН УССР (администр.) ВИЗРА (Всесоюзный Институт защиты растений) и проч. |               9.0 |       2.5 |
| Общение с людьми                                                                          |               7.0 |       6.5 |
| Развлечение (кино)                                                                        |               1.0 |       0.5 |
| Передвижение                                                                              |               3.0 |       8.5 |
| Домашние дела                                                                             |               4.0 |       2.5 |
| Отдых и купанье (18 раз, большей частью попутно)                                          |               3.0 |       3.0 |
| Резерв (непредвиденное)                                                                   |               1.0 |       --- |
|-------------------------------------------------------------------------------------------+-------------------+-----------|
| Всего                                                                                     |              98.0 |      93.0 |

Первые четыре раздела составляют учитываемую работу 1-й категории и
дают 56.0 эквивалентов (или 182 часа) по плану, фактически 66.5
веч. эквивал. или 216 часов.

Это время распределено следующим образом:



|    |                                                                            | Намечено | Выполнено |
|----+----------------------------------------------------------------------------+----------+-----------|
| А. | Основн. научная работа                                                     | 32ч.     | 38ч.      |
|    | Изучение математической статистики                                         | 25ч.     | 26ч. 20м. |
|    | Прочая литература                                                          | 7ч.      | 7ч. 45м.  |
|    | Научные письма                                                             | -        | 3ч. 55м.  |
| Б. | Прикладная биология (по сельскохоз. вредителям и др. насекомым) и экология | 70ч.     | 82ч. 15м. |
|    | Обработка материалов сотрудников в Киеве                                   | 21ч.     | 22ч.      |
|    | Обработка материалов сотрудников ВИЗРА и отделения ВИЗРА в Славянской      | 22ч.     | 26ч.      |
|    | Обработка материалов станции защиты растений в Ереване                     | 25ч.     | 32ч. 5м.  |
|    | Обработка данных станции защ. растений на Северном Кавказе (Верблюд)       | 2ч.      | 1ч. 20м.  |
| В. | Систематическая энтомология                                                | 77ч.     | 92ч. 40м. |
|    | Изучение личинок двух видов майского хруша                                 | 43ч.     | 32ч.      |
|    | Экскурсии и разбор насекомых                                               | 30ч.     | 46ч.      |
|    | Пренаровка земляных блошек (по плану 30 самцов, фактически 56 самцов)      | 4ч.      | 10ч.      |
|    | Мелочи (починка сачка и проч.)                                             | -        | 2ч.       |
| Г. | Организационная работа (отчет и план)                                      | 3ч.      | 3ч. 5м.   |
|----+----------------------------------------------------------------------------+----------+-----------|
|    | Всего                                                                      | 182ч.    | 216ч.     |

/(TODO. Объединить в последней строке два первых столбца в один.)/

Из этой общей работы проделано в отбросах времени (трамваи, пароходы,
поезда и т.д.):

|                           |           |
|---------------------------+-----------|
| Математическая статистика | 17ч. 50м. |
| Научная литература        | 7ч. 45м.  |
| Попутные экскурсии        | 4ч. 35м.  |
|---------------------------+-----------|
| Всего                     | 29ч. 30м. |

/(TODO. Тут разве во "Всего" не должно быть 30ч.10м.?)/

Кроме того, проделана учитываемая работа 2-й категории --- чтение
беллетристики (анг.: Твен и Бенсон) — 5ч. 45м.

В качестве примера годового плана и отчета приведу вкратце таковой за
1949 год, являющийся в общем тоже удачным годом.

Грубое распределение времени (в вечерних эквивалентах)

|                                                                                    | Намечено по плану | Исполнено |
|------------------------------------------------------------------------------------+-------------------+-----------|
| Учитываемая работа 1-й категории                                                   |               465 |     477.0 |
| Научное общение (общества и проч.)                                                 |                15 |      13.0 |
| Общественная работа                                                                |                15 |       9.0 |
| Служба в Кирг. Филиале АН СССР. проч. служба, попул. лекции и пр.                  |                30 |         - |
| Общение с людьми                                                                   |               180 |     169.0 |
| Передвижение                                                                       |               110 |     104.0 |
| Развлечения (1 опера, 2 балета, 3 оперетки, 7 драм, 11 концертов и проч., 47 кино) |                35 |      45.5 |
| Домашние дела                                                                      |                50 |        54 |
| Отдых и беллетристика                                                              |                45 |      90.5 |
| Резерв (болезнь, лечение и пр.)                                                    |                30 |      41.5 |
|------------------------------------------------------------------------------------+-------------------+-----------|
| Всего                                                                              |              1095 |    1095.0 |


Учитываемая работа 1-й категории (по плану 465 веч.  эквивал., или
1550 часов, фактически 477 веч. эквивал., или 1564ч. 15м.)
распределяется так:

|      |                                                              | По плану | Выполнено              |
|------+--------------------------------------------------------------+----------+------------------------|
| *А.* | *Основная научная работа*                                    | *235ч.*  | *213ч.80м.(точно 80?)* |
|   1. | Оригинальная работа                                          | 75ч.     |                        |
|   2. | Математика (математич. статистика)                           | 20ч.     | 20ч.30м.               |
|   3. | Научная литература                                           | 150ч.    | 103ч.15м.              |
|   4. | Научная переписка                                            | 20ч.     | 40ч.50м.               |
|   5. | Научные заметки                                              | 10ч.     | 17ч.55м.               |
|   6. | Библиография                                                 | 50ч.     | 31ч.                   |
| *Б.* | *Педагогич. биология и популяризация*                        | *150ч.*  | *179ч.15м.*            |
|      | Обработка материалов четырех аспирантов                      | 125ч.    | 148ч.                  |
|      | Консультация и помощь в обработке                            | 25ч.     | 31ч.15м.               |
| *В.* | *Экология и прикладная биология*                             | *240ч.*  | *416ч.10м.*            |
|   1. | Подготовка к печати работы по методике количественного учета | 40ч.     | 107ч.45м.              |
|   2. | Отчет по подгрызающим совкам                                 | 50ч.     | 198ч.05м.              |
|   3. | Наблюдения, записи и пр. по подгрызающим совкам              | 70ч.     | 51ч.                   |
|   4. | Литература по подгрызающим совкам                            | 50ч.     | 45ч.15м.               |
|   5. | Регистрация сборов насекомых                                 | 30ч.     | 11ч.05м.               |
| *Г.* | *Систематическая энтомология*                                | *745ч.*  | *667ч.30м.*            |
|   1. | Писал работу о блошках Киргизии шесть печатных листов        | 120ч.    | 173ч.05м.              |
|   2. | Обработка измерений по блошкам                               | 100ч.    | 53ч.45м.               |
|   3. | Определение киргизских блошек                                | 120ч.    | 206ч.30м.              |
|   4. | Монтировка блошек                                            | 70ч.     | 21ч.35м.               |
|   5. | Литература по блошкам                                        | 40ч.     | 22ч.                   |
|   6. | Экскурсии по сбору насекомых                                 | 150ч.    | 44ч.40м.               |
|   7. | Разбор материала после экскурсий                             | 100ч.    | 43ч.30м.               |
|   8. | Обменная переписка, мелочи                                   | 45ч.     | 21ч.35м.               |
|   9. | Вне плана систематика подгрызающих совок                     | -        | 80ч.50м.               |
| *Д.* | *Организационная работа*                                     | *90ч.*   | *37ч.50м.*             |
|      | Отчет за 1948г. и план на 1949г.                             | 22ч.     | 20ч.20м.               |
|      | Месячные планы и отчеты                                      | 35ч.     | 32ч.                   |
|      | Порядок в архивах                                            | 33ч.     | 35ч.30м.               |
|------+--------------------------------------------------------------+----------+------------------------|
|      | *Всего*                                                      |          | *1550ч.*               |

/(TODO. Выровнять "Всего" по правому краю клетки.)/

Из этого количества в отбросах времени проделано:

|      |                                              | *По плану* | *Фактически* |
|------+----------------------------------------------+------------+--------------|
| *А.* | *Основн. научной работы*                     | *120ч.*    | *100ч.35м.*  |
|      | Математич. статистика                        | 20ч.       | 20ч.50м.     |
|      | Литература                                   | 100ч.      | 79ч.45м.     |
| *Б.* | *Педагогическая биология*                    | *25ч.*     | *2ч.15м.*    |
| *В.* | *Экология и прикладная биология: литература* | *25ч.*     | *22ч.50м.*   |
| *Г.* | *Системат. энтомология*                      | *115ч.*    | *56ч.55м.*   |
|      | Обработка измерений (в поезде)               | 75ч.       | 36ч.15м.     |
|      | Попутные экскурсии                           | 40ч.       | 20ч.40м.     |
| *Д.* | *Организационная работа*                     | *15ч.*     | *2ч.20м.*    |
|------+----------------------------------------------+------------+--------------|
|      | *Всего*                                      | *300ч.*    | *184ч.55м.*  |

/(Было написано 55ч в строке Всего, исправил на "м".)/

Кроме того, учтена работа 2-й категории

|                                         |         |             |
|-----------------------------------------+---------+-------------|
| Слушание докладов на научн. обществ.    | 80ч.    | 41ч.30м.    |
| Литература общеобразов. и беллетристика | 220ч.   | 261ч.45м.   |
|-----------------------------------------+---------+-------------|
| *Всего*                                 | *300ч.* | *303ч.15м.* |


Работы не прочитанные, а только просмотренные, учитывались только по
времени в отделе библиографии.

Те же книги по языку, на котором написаны:

|                      |          |         |
|----------------------+----------+---------|
|                      | Намечено | Фактич. |
| На русском языке     | 8500с.   | 11571с. |
| На французском языке | 3000с.   | 1960с.  |
| английском           | 1500с.   | 409с.   |
| немецком             | 1000с.   | -       |
|----------------------+----------+---------|
| *Всего*              | 14000с.  | 13940с. |









** Количество времени должно соответствовать качеству работы


Во втором пункте я указываю, что имеющееся время должно быть
распределено так, чтобы качество времени соответствовало качеству
работы. Что это значит? Например, дома тратится время на чтение
художественной литературы. Никто не говорит, что не нужно читать
художественную литературу, но ее надо читать тогда, когда невозможно
заниматься более интенсивно. А дома, за столом, чем можно заниматься?
Проработкой книг в форме рефератов и конспектов, монтировкой и
определением насекомых --- ведь иначе как за столом вы этим делом
заниматься не можете. Читать легкую литературу, в частности
иностранную в целях изучения иностранного языка, можно в любых
условиях. После окончания университета мне часто приходилось ездить в
трамваях, бывать в командировках. Время, потраченное на поездки, по
моей классификации считалось "отбросом времени", и я старался его
максимально использовать. Я знаю очень прилично три языка:
французский, немецкий, английский. Я читаю на этих языках свободно и
могу сразу переводить без словаря, и знаю их вовсе не потому, что у
меня какие-то особенные способности к ним. У меня сохранились
аттестационные ведомости за реальное училище, в котором я учился, и
там по немецкому языку у меня есть тройки, четверки и только в
последних классах я имел пятерки. Когда я окончил училище, то немецкую
грамматику знал хорошо, но читать без словаря не мог. Я начал изучать
язык, пользуясь немецким определителем насекомых. Что касается
английского языка, то я могу сказать, выражаясь образно, я на медные
деньги учен. В университете я слушал лекции по 2 часа в неделю, потом
я два лета занимался самостоятельно по утрам со словарем, затем стал
читать английскую литературу в трамвае и постепенно переключился к
более квалифицированным видам работ. В Ленинграде мне приходилось
ездить на работу далеко, около часу приходилось ехать в трамвае и я
это время использовал для чтения иностранной литературы. Французский
язык, я, правда, знал с детства.

У меня страдает фонетика и мое английское произношение весьма
дефектно. Очень хорошо, конечно, освоить фонетику, но для научного
работника фонетика --- это вещь второстепенная, основное для научного
работника --- знакомство с литературой. Я вовсе не хочу вас
расхолаживать в отношении изучения фонетики, но я хочу подчеркнуть
необходимость в первую очередь научиться читать литературу.

Таким образом, языки я почти целиком изучил на железных дорогах, в
трамваях, в очередях, в ожидании приема у врача и т.д. Начал
заниматься я, например, аглийским языком с 1907г. и за 30 лет очень
пополнил запас слов, ознакомился с французской, немецкой и английской
литературой и сейчас могу читать любое произведение. Несмотря на мои
дефекты в произношении, я в Ленинграде в 1934—36 годах был
переводчиком приезжающих иностранных ученых-биологов. Я справлялся
хорошо с переводом потому, что у меня был большой запас слов, и потому
что у меня не было ложного самолюбия, что является крупным
дефектом. Один мой приятель, который часто бывал за границей, терялся,
когда его сразу не понимали. Я же, если меня не понимали, повторял 2--3
раза и в конце концов меня понимали. Надо более спокойно относиться к
временным неудачам, не следует иметь ложного самолюбия.

Каждому научному работнику необходимо делать большой упор на изучение
иностранных языков. Сейчас изучению иностранных языков придается
большое значение: открываются факультеты иностранных языков и
проводятся другие мероприятия. В с Вестнике "Высшей школы" я недавно
прочел о неутверждении в звании кандидата наук одного диссертанта и в
числе причин неутверждения было указано неиспользование иностранной
литературы. Сейчас правильно указывается, что борьба с
низкопоклонством перед заграницей не означает игнорирование изучения
иностранной литературы.

Итак, необходимо "отбросы времени" использовать в максимальной степени
на изучение иностранных языков.

** Использование отбросов времени

Привычка использования "отбросов времени" дает возможность
использовать его все более квалифицированно: начать надо с чтения
беллетристики, исторических и других произведений. Постепенно
начинаешь, даже в пределах "отбросов времени", делать все более и
более квалифицированную работу. Есть такой прибор логарифмическая
линейка. Я часто использую "отбросы времени" для статистической
обработки материалов, пользуясь логарифмической линейкой. Когда мне
говорят, что это невозможно, то я обычно говорю: "Сейчас не можете,
надо тренироваться. Я сам не всегда мог, а постепенно привык". Можно
так приучить себя отстраиваться от обстановки, что начинаешь работать
в обстановке, когда тебе, казалось бы, мешают. При поездках по
железной дороге я лично бываю доволен, когда попадаю в детский
вагон. Дети мне не мешают, а преимуществом (чисто эгоистическим)
детских вагонов является то, что в детском вагоне обычно кто-нибудь не
спит и сам можешь спать спокойно, не боясь, что тебя обкрадут.

Когда я работал в ВИЗРа, мне приходилось часто бывать в
командировках. Обычно в поезд я забирал определённое количество книг,
если командировка предполагалась быть длительной, то я посылал в
определенные пункты посылку с книгами.  Количество книг, бравшихся с
собой, исчислялось исходя из прошлого опыта.

Как распределялось чтение книг в течение дня? С утра, когда голова
свежая, я беру серьезную литературу (по философии, по
математике). Когда я проработаю полтора--два часа, я перехожу к более
легкому чтению --- историческому или биологическому тексту. Когда
голова усталая, то берешь беллетристику.

Какие преимущества дает чтение в дороге? Во-первых, не чувствуешь
неудобства в дороге, легко с ним миришься; во-вторых, нервная система
находится в лучшем состоянии, чем в других, условиях.

Для трамваев у меня тоже не одна книжка, а две или три. Если едешь с
какого-либо конечного пункта (напр., в Ленинграде), то можно сидеть,
следовательно, можно не только читать, но и писать. Когда же едешь в
переполненном трамвае, а иногда и висишь, то тут нужна небольшая
книжечка и более легкая для чтения. Сейчас в Ленинграде много народу
читает в трамваях.

Вот как можно использовать много времени из того, которое обычно
пропадает.

На заседаниях я занимался зачастую решением задач, причем без ущерба
для моей деятельности, как члена заседания. Сначала мое поведение
вызвало протест, а потом, видя мою активность как члена заседания
(реплики, выступления), перестали протестовать.

Использование "отбросов времени" важно потому, что вы его используете
на то, что в обычное время у вас времени не хватает, а тем самым вы
можете поддерживать разносторонность ваших интересов. Мы, например,
живем в провинции, здесь нет таких больщих библиотек, как в Москве и в
Ленинграде, но когда у вас разнообразные интересы, то вы всегда, даже
в небольшой районной библиотеке, найдете для себя много
интересного. Если человек является узким специалистом, то для него
необходимо существование в больших городах, тогда как пребывание в
большом городе, хоти к этому очень многие стремятся, вовсе не является
обязательным условием для умственного развития, тем более, что жители
больших городов зачастую все возможности большого города не
используют.

В качестве "отбросов времени" можно считать пешее хождение.
Пешеходным видом передвижения прежде всего надо пользоваться в
гигиенических целях. Тут нужно привести в пример И.П. Павлова.
Павлов, будучи большим сторонником физкультуры, помимо прямых ее видов
(гимнастики и пр.) всегда широко использовал "отбросы времени" на
сохранение собственного здоровья. Он много ходил пешком, не
пользовался трамваем.

Я считаю, что на расстояние в 2--3 километра нерентабельно ехать на
трамвае. При поездке на трамвае на такое расстояние вы много времени
не сэкономите. Максимум, что вы можете сэкономить 5--7 минут, учитывая
ожидание трамвая, но зато вы рискуете потерей здоровья при этом
ожидании, а кроме того, не используете времени для упражнения ваших
ног. Поэтому, даже в условиях города я не советую пользоваться
трамваем при близких расстояниях, другое дело, когда расстояние
большое. Я лично всегда стараюсь, где это возможно, ходить пешком для
тренировки ног.

В летнее время особенно нужно тренироваться в пешем хождении. Один
пример использования "отбросов времени", который я лично наблюдал в
Крыму. Шла одна женщина и у нее на коромысле прялка. Идет и
прядет. Я, конечно, прядением не занимался, но летние пешеходные
прогулки старался использовать на сборы насекомых. Работая в ВИЗРа, я
порядочно странствовал по стране и все переходы старался делать пешком
и ловить насекомых. Благодаря этому я составил большую коллекцию и
сейчас занимаюсь обработкой материала для специальной работы и для
нашей "Фауны" по земляным блошкам.

** Необходимость разнообразия работ

Разнообразие работы также является важным гигиеническим приемом.

Я был знаком с одним профессором механики в Баку, который в качестве
отдыха изучал языки. Очевидно, эти два раздела науки как-то разобщены
в нашем мозгу. Мой приятель знал много европейских языков, а за 8 лет
изучил 5 языков: тюркский, грузинский (составил словарь), армянский,
арабский и персидский. И все это в порядке отдыха. А это не был
крупный ученый. Он был просто человек очень высокой культуры, который
использовал все свободное время на изучение языков.

Гаусс в порядке отдыха изучил русский язык и читал Лобачевского на
русском языке.

Занятия систематикой также можно рекомендовать молодым
биологам. Насекомых легко собирать, они занимают мало места, а
потребность в систематиках сейчас большая. Сейчас фронт систематиков
далеко не является сплошным, по многим группам нет ни одного
специалиста, и даже по такому важному семейству, как пчелиные,
проверить определение не легко. Этой работой не обязательно заниматься
как основной работой. Эти занятия имеют огромное значение как форма
культурного отдыха, и очень многие крупные специалисты-систематики не
являлись профессиональными учёными. Специалист по хищникам был
нотариус в Австрии, систематикой занимались инженеры, офицеры, аббаты
и у меня есть знакомый, официальная должность которого --- инспектор
Военной коллегии Верховного суда, который, приходя домой, ежедневно
занимался божьими коровками; он написал большую монографию, у него
масса рисунков и он сам говорит, что для него эта форма деятельности
является великолепнейшей формой отдыха. Есть люди, которые собирают
для отдыха марки, спичечные коробки. Ничего плохого в этом нет, но
этим они никакого вклада в науку не делают, а когда вы занимаетесь
насекомыми или другими объектами природы, то вы можете внести вклад в
науку, от изучения местной фауны до участия, например, в издании АН
СССР "Фауны СССР". Почему прозевали во Франции появление колорадского
жука? Очевидно, потому, что энтомологи были на фронте. Поэтому наличие
большого количества любителей-систематиков является очень важным
государственным делом.

Я сам занимаюсь систематикой глубже, чем обычные систематики, и для
меня эти занятия очень полезны, они действуют очень благотворно на мою
нервную систему.

Моя система способствует повышению продуктивности работы и вместе с
тем является прекрасным эквивалентом санатория. В Крыму мне самому
говорили, что большинство отдыхающих уезжает из санаториев и домов
отдыха на 2--3 дня раньше положенного срока, говоря, что скучно,
нечего делать. Нечего делать! Это в Крыму-то!

Я уже указывал вам, что путем постоянной тренировки вы значительно
увеличите свою работоспособность, и потому я рекомендую попытаться
применить систему в порядке опыта.

Каковы достоинства этой системы?
1. Повышение эффективности. Это иллюстрация к словам поэта: "Ты сам
   свой высший суд". Она приучает к точному учету всего того, что
   проделано, и к самоконтролю.
2. Полезно отражается на здоровье, избавляет от скуки, от возможности
   говорить, что "нечего делать".
3. Самокритнка, самопонимание увеличивается тогда, когда вы видите
   насколько вы правильно используете любое время.

Правда, дефектом моей системы является то, что от учета времени
несколько страдают окружающие, так как они чувствуют, что каждое
отвлечение от занятий учитывается. Но постепенно и к этому привыкают.

Я для себя этой тяжести не ощущаю, напротив, когда я не впишу данные о
проделанном, то я неудовлетворен.
